#INDEX ERROR
#names=["kerem", "ali"]
#print(names[2])

#KEY ERROR
#my_dict={"name":"kerem", "surname":"reyhani"}
#print(my_dict["nme"])

#NAME ERROR
#print(kerem)

#ATTRIBUTE ERROR
#my_list=["ahmet", 28]
#my_list.append("mehmet")
#print(my_list)
#my_list.appen("mahmut")
#print(my_list)

#INDENTATION ERROR
#my_list=["ahmet", "mehmet", "kerem"]
#for x in my_list:
#print(x)

#TYPE ERROR
#print("10" + 10)

#VALUE ERROR
#print(int("100.7"))